kind: Deployment
apiVersion: apps/v1
metadata:
  name: task-manager-ui
spec:
  selector:
    matchLabels:
      app: task-manager-ui
      name: task-manager-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: task-manager-ui
        name: task-manager-ui
    spec:
      containers:
        - name: task-manager-ui
          image: bom.ocir.io/bmkvfx57mojv/task-manager-ui:0.0.1
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_ENDPOINT
              value: "146.56.52.190:8080"
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: task-manager-secret