kind: Service
apiVersion: v1
metadata:
  name: task-manager-ui
  namespace: default
spec:
    selector:
      app: task-manager-ui
    type: LoadBalancer
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 3000